import React from 'react';
import './FaceRecognition.css';

const FaceRecognition = ({ boxes = [], imageUrl, faceData = [], colorData = [], isLoading, analysisCount, onImageLoad }) => {
  const hasAnalysis = imageUrl && !isLoading && analysisCount > 0;
  const hasData = faceData.length > 0 || colorData.length > 0;
  if (!imageUrl && !isLoading) return <section className="empty-state"><span className="empty-icon">⌁</span><h2>Pronto per l’analisi</h2><p>Carica un’immagine o prova l’esempio per visualizzare i risultati.</p></section>;
  return <section className="results-layout" aria-live="polite">
    <div className="image-card"><div className="image-card-head"><span>INPUT IMAGE</span><span>{isLoading ? 'ELABORAZIONE' : hasData ? 'ANALIZZATA' : 'PRONTA'}</span></div><div className="image-stage">{imageUrl && <img id="inputimage" alt="Immagine sottoposta all’analisi" src={imageUrl} onLoad={onImageLoad} />}{isLoading && <div className="loading-overlay"><span className="loader" /><p>Sto analizzando volto e palette…</p></div>}{!isLoading && boxes.map((box, index) => <div key={index} className="bounding-box" style={{ top: box.topRow, left: box.leftCol, width: box.rightCol - box.leftCol, height: box.bottomRow - box.topRow }}><span>Face {index + 1}</span></div>)}</div></div>
    <aside className="results-card"><div className="results-head"><div><p className="section-kicker">OUTPUT</p><h2>Risultati</h2></div><span className="analysis-index">#{String(analysisCount).padStart(2, '0')}</span></div>{!hasAnalysis && !isLoading && <p className="results-placeholder">Immagine pronta. Clicca “Analizza il file” per avviare il rilevamento.</p>}{isLoading && <p className="results-placeholder">Analisi in corso…</p>}{hasAnalysis && !hasData && <p className="results-placeholder">Analisi completata: nessun volto o colore rilevabile. Prova un’altra immagine.</p>}{hasData && <><div className="metric"><span>Volti rilevati</span><strong>{faceData.length}</strong></div>{faceData.length > 0 && <div className="confidence-list">{faceData.map((face, index) => <div className="confidence-row" key={index}><span>Rilevamento {index + 1}</span><b>{Math.round((face.value || 0) * 100)}%</b></div>)}</div>}<div className="divider" /><h3>Colori dominanti</h3><div className="colour-list">{colorData.slice(0, 6).map((colour, index) => <div className="colour-row" key={`${colour.raw_hex}-${index}`}><span className="swatch" style={{ backgroundColor: colour.raw_hex }} /><span>{colour.w3c?.name || colour.raw_hex}</span><b>{Math.round((colour.value || 0) * 100)}%</b></div>)}</div></>}</aside>
  </section>;
};
export default FaceRecognition;
